# Generated by Django 6.0.7 on 2026-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofdelivery',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Awaiting customer confirmation'), ('confirmed', 'Confirmed by customer'), ('disputed', 'Disputed by customer')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='dispute_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
