# Generated by Django 6.0.7 on 2026-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_proofofdelivery_confirmation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofdelivery',
            name='confirmed_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
