# Generated by Django 6.0.7 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_proofofdelivery_confirmed_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('en_route', 'En Route'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('delivered', 'Delivered'), ('disputed', 'Disputed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=25),
        ),
    ]
