# Generated by Django 6.0.7 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('en_route', 'En Route'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('delivered', 'Delivered'), ('disputed', 'Disputed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
